// projects.js - Project data
// This file defines the PROJECTS array used by the portfolio.

const PROJECTS = [
  {
    id: "barber-shop",
    featured: true,
    isMobile: true,
    featuredScreens: [0, 3], // highlight these screens in the gallery
    name: "Barber Shop",
    subtitle: "Haircut & Grooming Platform",
    emoji: "✂️",
    image: "img/barber/barbershop-0.png",
    imgStyle: "",
    tags: ["Figma"],
    mainTags: ["Figma"],
    shortDesc:
      "A sleek Figma design for a barber booking platform, covering onboarding, service browsing, and appointment scheduling.",
    linkText: "View project →",
    year: "2025",
    role: "UI/UX Designer",
    client: "Louweben Maquizo",
    overview:
      "A complete UI/UX design for a haircut and grooming booking app, designed entirely in Figma. The project covers the full customer journey — from sign up and login, through browsing services and barbers, to booking and managing appointments — with a consistent visual system built around reusable components and a light, editorial style.",
    responsibilities: [
      "Designed the end-to-end user flow, from onboarding and login to booking confirmation",
      "Built a reusable Figma component library (buttons, inputs, cards, nav) for consistent styling across screens",
      "Created high-fidelity mockups for both mobile and desktop breakpoints",
      "Designed the service catalog, barber profiles, and appointment scheduling screens",
      "Established a visual style guide covering typography, color palette, and spacing tokens",
      "Prototyped key interactions (booking flow, login/register, form states) using Figma's interactive prototyping tools",
      "Conducted informal usability walkthroughs with the client to refine navigation and layout",
      "Iterated on designs based on client feedback across multiple review rounds",
    ],
    techStack: ["Figma"],
    figmaUrl:
      "https://www.figma.com/design/eo6TnccTbwsf6lyh8rmYdp/Untitled?node-id=2015-179&t=xOKo05UFVQROldyt-1",
    galleryImages: [
      "img/barber/barbershop-0.png",
      "img/barber/barbershop-1.png",
      "img/barber/barbershop-2.png",
      "img/barber/barbershop-3.png",
      "img/barber/barbershop-4.png",
      "img/barber/barbershop-5.png",
      "img/barber/barbershop-6.png",
      "img/barber/barbershop-7.png",
      "img/barber/barbershop-8.png",
      "img/barber/barbershop-9.png",
      "img/barber/barbershop-10.png",
    ],
  },
  {
    id: "barangay-document-system",
    featured: true,
    isMobile: false,
    featuredScreens: [0, 1],
    name: "Barangay Document Request",
    subtitle: "E-Government & Civic Services Platform",
    emoji: "🏛️",
    image: "img/baranngay/baranggay-0.png",
    imgStyle: "",
    tags: ["Figma"],
    mainTags: ["Figma"],
    shortDesc:
      "A Figma-designed online document request system for a barangay office, enabling residents to request official documents digitally — fast, secure, and hassle-free.",
    linkText: "View project →",
    year: "2025",
    role: "UI/UX Designer",
    client: "Barangay Prk. Dimausog, Davao City",
    overview:
      "A complete UI/UX design for a Barangay Online Document Request System, created in Figma. The system serves both residents and barangay administrators — residents can log in, request official documents (barangay clearance, certificates, etc.), track request status, and manage their accounts, while admins can process and approve requests. The design prioritizes clarity, accessibility, and ease of use for a government civic services context.",
    responsibilities: [
      "Designed the full resident and admin portal UI flows from login to document request completion",
      "Created a clean, accessible design system with a consistent orange-and-white color palette reflecting civic identity",
      "Designed the resident dashboard with document request cards, announcement boards, and transaction day schedules",
      "Designed the step-by-step request flow: request form, payment method selection, and appointment confirmation",
      "Designed the admin panel for reviewing, processing, and approving document requests",
      "Built reusable Figma components: form fields, buttons, status badges, sidebar navigation, and notification icons",
      "Established a visual style guide covering typography hierarchy, color tokens, spacing, and icon usage",
      "Conducted design walkthroughs with stakeholders to validate flows and refine the user experience",
    ],
    techStack: ["Figma"],
    figmaUrl: "#",
    galleryImages: [
      "img/baranngay/baranggay-1.png",
      "img/baranngay/baranggay-2.png",
      "img/baranngay/baranggay-3.png",
      "img/baranngay/baranggay-4.png",
      "img/baranngay/baranggay-5.png",
      "img/baranngay/baranggay-6.png",
      "img/baranngay/baranggay-7.png",
      "img/baranngay/baranggay-8.png",
      "img/baranngay/baranggay-9.png",
      "img/baranngay/baranggay-10.png",
    ],
  },
];
