const PROJECTS = [
  {
    id: 'metrics-dashboard',
    featured: true,
    name: 'Metrics Dashboard',
    subtitle: 'Analytics Platform',
    emoji: null,
    imgStyle: 'background:linear-gradient(135deg,#0A0E17 0%,#111830 100%);',
    tags: ['React', 'TypeScript', 'Recharts', 'Supabase'],
    mainTags: ['React', 'TypeScript'],
    shortDesc: 'Real-time analytics platform processing 2M+ events/day. Built with React Query for server state, WebSocket live updates, and a custom chart system.',
    linkText: 'View case study →',
    year: '2024',
    role: 'Lead Frontend Developer',
    client: 'Singapore FinTech Startup',
    overview: 'Designed and built a real-time SaaS analytics dashboard that processes over 2 million events per day. The platform gives product teams live visibility into user behavior, conversion funnels, and revenue metrics.',
    responsibilities: [
      'Architected the frontend with React, TypeScript, and React Query for efficient server-state management',
      'Built a custom charting layer on top of Recharts with real-time WebSocket data streaming',
      'Implemented role-based access control and multi-tenant workspace isolation',
      'Optimized bundle size and rendering — achieved 95+ Lighthouse performance score',
      'Collaborated with backend team on Supabase schema design and RLS policies'
    ],
    techStack: ['React', 'TypeScript', 'Recharts', 'Supabase', 'WebSockets', 'Tailwind CSS'],
    liveUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'ecommerce-platform',
    featured: false,
    name: 'E-commerce Platform',
    subtitle: 'Online Store',
    emoji: '🛒',
    imgStyle: 'background:#0A1520;',
    tags: ['Next.js', 'Stripe'],
    mainTags: ['Next.js'],
    shortDesc: 'Full-featured store with cart, Stripe checkout, and inventory management.',
    linkText: 'Live demo →',
    year: '2024',
    role: 'Full-Stack Developer',
    client: 'Retail Brand (US)',
    overview: 'End-to-end e-commerce solution with product catalog, shopping cart, Stripe payment integration, and an admin dashboard for inventory and order management.',
    responsibilities: [
      'Built the storefront with Next.js App Router and server-side rendering for SEO',
      'Integrated Stripe Checkout and webhooks for payment confirmation and refunds',
      'Developed admin panel for product CRUD, inventory tracking, and order fulfillment',
      'Implemented cart persistence with cookies and optimistic UI updates',
      'Set up automated deployment pipeline on Vercel with preview environments'
    ],
    techStack: ['Next.js', 'Stripe', 'PostgreSQL', 'Prisma', 'Tailwind CSS'],
    liveUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'ai-chat-api',
    featured: false,
    name: 'AI Chat API',
    subtitle: 'Conversational AI',
    emoji: '🤖',
    imgStyle: 'background:#0A1520;',
    tags: ['Python', 'FastAPI'],
    mainTags: ['Python'],
    shortDesc: 'REST API for conversational AI with streaming responses and context memory.',
    linkText: 'GitHub →',
    year: '2023',
    role: 'Backend Developer',
    client: 'Internal / Open Source',
    overview: 'A production-ready REST API that powers conversational AI applications with streaming responses, conversation memory, and pluggable LLM providers.',
    responsibilities: [
      'Designed RESTful API with FastAPI including OpenAPI documentation',
      'Implemented Server-Sent Events (SSE) for real-time streaming responses',
      'Built conversation context management with Redis for session persistence',
      'Added rate limiting, API key authentication, and usage analytics',
      'Wrote comprehensive test suite with pytest achieving 90%+ coverage'
    ],
    techStack: ['Python', 'FastAPI', 'Redis', 'OpenAI API', 'Docker'],
    liveUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'task-manager-app',
    featured: false,
    name: 'Task Manager App',
    subtitle: 'Mobile Productivity',
    emoji: '📱',
    imgStyle: 'background:#0A1520;',
    tags: ['Flutter', 'Firebase'],
    mainTags: ['Flutter'],
    shortDesc: 'Cross-platform mobile app with real-time sync and offline support.',
    linkText: 'App Store →',
    year: '2023',
    role: 'Mobile Developer',
    client: 'Productivity Startup',
    overview: 'Cross-platform task management app for iOS and Android with real-time sync across devices, offline-first architecture, and team collaboration features.',
    responsibilities: [
      'Built the entire mobile app in Flutter with clean architecture (BLoC pattern)',
      'Implemented Firebase Firestore for real-time data sync across devices',
      'Added offline support with local SQLite cache and conflict resolution',
      'Designed intuitive UI with drag-and-drop task reordering and swipe gestures',
      'Published to both App Store and Google Play with CI/CD via Codemagic'
    ],
    techStack: ['Flutter', 'Firebase', 'SQLite', 'BLoC', 'Dart'],
    liveUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'booking-system',
    featured: false,
    name: 'Booking System',
    subtitle: 'Scheduling Platform',
    emoji: '📅',
    imgStyle: 'background:#0A1218;',
    tags: ['Vue.js', 'Node.js', 'MongoDB'],
    mainTags: ['Vue.js'],
    shortDesc: 'Appointment scheduling platform with calendar sync and automated reminders.',
    linkText: 'View case study →',
    year: '2023',
    role: 'Full-Stack Developer',
    client: 'Healthcare Clinic Chain',
    overview: 'Online booking system for a multi-location healthcare clinic, handling appointment scheduling, doctor availability, and automated SMS/email reminders.',
    responsibilities: [
      'Developed Vue.js frontend with interactive calendar and time-slot picker',
      'Built Node.js/Express API with MongoDB for flexible scheduling rules',
      'Integrated Google Calendar sync for doctors and admin staff',
      'Implemented Twilio SMS and SendGrid email for appointment reminders',
      'Created admin dashboard for managing schedules, patients, and reports'
    ],
    techStack: ['Vue.js', 'Node.js', 'MongoDB', 'Twilio', 'SendGrid'],
    liveUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'portfolio-cms',
    featured: false,
    name: 'Portfolio CMS',
    subtitle: 'Content Management',
    emoji: '🎨',
    imgStyle: 'background:#0A1018;',
    tags: ['Next.js', 'Sanity', 'Vercel'],
    mainTags: ['Next.js'],
    shortDesc: 'Headless CMS-powered portfolio builder for creative professionals.',
    linkText: 'Live demo →',
    year: '2022',
    role: 'Frontend Developer',
    client: 'Creative Agency',
    overview: 'A portfolio website builder that lets designers and photographers manage their work through a headless CMS without touching code.',
    responsibilities: [
      'Built dynamic portfolio pages with Next.js ISR for fast load times',
      'Integrated Sanity CMS with custom schemas for projects, galleries, and blog posts',
      'Implemented image optimization pipeline with next/image and Cloudinary',
      'Created theme customization system with CSS variables',
      'Delivered 6 client portfolios within a 3-month engagement'
    ],
    techStack: ['Next.js', 'Sanity', 'Tailwind CSS', 'Vercel', 'Cloudinary'],
    liveUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'inventory-tracker',
    featured: false,
    name: 'Inventory Tracker',
    subtitle: 'Warehouse Management',
    emoji: '📦',
    imgStyle: 'background:#0A0F14;',
    tags: ['React', 'Django', 'PostgreSQL'],
    mainTags: ['React'],
    shortDesc: 'Warehouse inventory system with barcode scanning and low-stock alerts.',
    linkText: 'View case study →',
    year: '2022',
    role: 'Full-Stack Developer',
    client: 'Logistics Company',
    overview: 'Internal warehouse management tool that tracks inventory levels, processes inbound/outbound shipments, and sends alerts when stock runs low.',
    responsibilities: [
      'Built React dashboard with real-time inventory counts and search/filter',
      'Developed Django REST API with PostgreSQL for transactional data integrity',
      'Integrated barcode scanner via device camera using QuaggaJS',
      'Implemented automated low-stock email alerts and reorder suggestions',
      'Migrated legacy Excel-based tracking — reduced errors by 80%'
    ],
    techStack: ['React', 'Django', 'PostgreSQL', 'Redis', 'Docker'],
    liveUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'weather-app',
    featured: false,
    name: 'Weather App',
    subtitle: 'Mobile Utility',
    emoji: '🌤️',
    imgStyle: 'background:#0A1420;',
    tags: ['Flutter', 'OpenWeather API'],
    mainTags: ['Flutter'],
    shortDesc: 'Beautiful weather app with 7-day forecasts and location-based alerts.',
    linkText: 'App Store →',
    year: '2022',
    role: 'Mobile Developer',
    client: 'Personal Project',
    overview: 'A polished weather application with animated UI, 7-day forecasts, hourly breakdowns, and severe weather push notifications.',
    responsibilities: [
      'Designed and built UI in Flutter with custom weather animations',
      'Integrated OpenWeather API with geolocation for automatic city detection',
      'Implemented Firebase Cloud Messaging for severe weather alerts',
      'Added widget support for home screen quick-glance weather',
      'Achieved 4.8★ rating on Google Play with 10k+ downloads'
    ],
    techStack: ['Flutter', 'OpenWeather API', 'Firebase', 'Dart'],
    liveUrl: '#',
    githubUrl: '#'
  }
];
