// projects.js - Project data
// This file defines the PROJECTS array used by the portfolio.

const PROJECTS = [
  {
    id: "barber-shop",
    featured: true,
    isMobile: true,
    featuredScreens: [0, 3], // highlight these screens in the gallery
    name: "Barber Shop",
    subtitle: "Haircut & Grooming Platform",
    emoji: "✂️",
    image: "img/barber/barbershop-0.png",
    imgStyle: "",
    tags: ["Figma"],
    mainTags: ["Figma"],
    shortDesc:
      "A sleek Figma design for a barber booking platform, covering onboarding, service browsing, and appointment scheduling.",
    linkText: "View project →",
    year: "2025",
    role: "UI/UX Designer",
    client: "Louweben Maquizo",
    overview:
      "A complete UI/UX design for a haircut and grooming booking app, designed entirely in Figma. The project covers the full customer journey — from sign up and login, through browsing services and barbers, to booking and managing appointments — with a consistent visual system built around reusable components and a light, editorial style.",
    responsibilities: [
      "Designed the end-to-end user flow, from onboarding and login to booking confirmation",
      "Built a reusable Figma component library (buttons, inputs, cards, nav) for consistent styling across screens",
      "Created high-fidelity mockups for both mobile and desktop breakpoints",
      "Designed the service catalog, barber profiles, and appointment scheduling screens",
      "Established a visual style guide covering typography, color palette, and spacing tokens",
      "Prototyped key interactions (booking flow, login/register, form states) using Figma's interactive prototyping tools",
      "Conducted informal usability walkthroughs with the client to refine navigation and layout",
      "Iterated on designs based on client feedback across multiple review rounds",
    ],
    techStack: ["Figma"],
    figmaUrl:
      "https://www.figma.com/design/eo6TnccTbwsf6lyh8rmYdp/Untitled?node-id=2015-179&t=xOKo05UFVQROldyt-1",
    galleryImages: [
      "img/barber/barbershop-0.png",
      "img/barber/barbershop-1.png",
      "img/barber/barbershop-2.png",
      "img/barber/barbershop-3.png",
      "img/barber/barbershop-4.png",
      "img/barber/barbershop-5.png",
      "img/barber/barbershop-6.png",
      "img/barber/barbershop-7.png",
      "img/barber/barbershop-8.png",
      "img/barber/barbershop-9.png",
      "img/barber/barbershop-10.png",
    ],
  },
  {
    id: "barangay-document-system",
    featured: true,
    isMobile: false,
    featuredScreens: [0, 1],
    name: "Barangay Document Request",
    subtitle: "E-Government & Civic Services Platform",
    emoji: "🏛️",
    image: "img/baranngay/baranggay-0.png",
    imgStyle: "",
    tags: ["Figma"],
    mainTags: ["Figma"],
    shortDesc:
      "A Figma-designed online document request system for a barangay office, enabling residents to request official documents digitally — fast, secure, and hassle-free.",
    linkText: "View project →",
    year: "2025",
    role: "UI/UX Designer",
    client: "Cherry Mae Medija Mandalano",
    overview:
      "A complete UI/UX design for a Barangay Online Document Request System, created in Figma. The system serves both residents and barangay administrators — residents can log in, request official documents (barangay clearance, certificates, etc.), track request status, and manage their accounts, while admins can process and approve requests. The design prioritizes clarity, accessibility, and ease of use for a government civic services context.",
    responsibilities: [
      "Designed the full resident and admin portal UI flows from login to document request completion",
      "Created a clean, accessible design system with a consistent orange-and-white color palette reflecting civic identity",
      "Designed the resident dashboard with document request cards, announcement boards, and transaction day schedules",
      "Designed the step-by-step request flow: request form, payment method selection, and appointment confirmation",
      "Designed the admin panel for reviewing, processing, and approving document requests",
      "Built reusable Figma components: form fields, buttons, status badges, sidebar navigation, and notification icons",
      "Established a visual style guide covering typography hierarchy, color tokens, spacing, and icon usage",
      "Conducted design walkthroughs with stakeholders to validate flows and refine the user experience",
    ],
    techStack: ["Figma"],
    figmaUrl:
      "https://www.figma.com/design/RpRTps7Wz9yCFKR0ep59uy/Library-Management-System?node-id=0-1&t=lRgLq1p43tjDp5Tq-1",
    galleryImages: [
      "img/baranngay/baranggay-1.png",
      "img/baranngay/baranggay-2.png",
      "img/baranngay/baranggay-3.png",
      "img/baranngay/baranggay-4.png",
      "img/baranngay/baranggay-5.png",
      "img/baranngay/baranggay-6.png",
      "img/baranngay/baranggay-7.png",
      "img/baranngay/baranggay-8.png",
      "img/baranngay/baranggay-9.png",
      "img/baranngay/baranggay-10.png",
    ],
  },
  {
    id: "champion",
    featured: true,
    isMobile: true,
    featuredScreens: [1, 5],
    name: "Champion",
    subtitle: "Refer & Earn Mobile App",
    emoji: "🏆",
    image: "img/champion/mobile-0.png",
    imgStyle: "",
    tags: ["Figma"],
    mainTags: ["Figma"],
    shortDesc:
      "A Figma-designed mobile app for Champion — a refer-and-earn platform where users invite friends, track referrals, and earn real money rewards.",
    linkText: "View project →",
    year: "2025",
    role: "UI/UX Designer",
    client: "Champion App",
    overview:
      "Champion is a Figma UI/UX design for a referral-based earnings app. Users sign up, refer friends via a unique link, and earn money for every successful referral. The design covers the full user journey — from onboarding and sign-in through the dashboard, referral tracking, contest participation, and payout management. Both mobile and tablet breakpoints were designed, giving the app a consistent, bold experience across devices.",
    responsibilities: [
      "Designed the full onboarding, sign-up, and sign-in flow for the mobile app",
      "Built the user dashboard showing total earnings, referral stats, and transaction history",
      "Designed the referral flow: unique link sharing, champions list, and referral status tracking",
      "Created contest and rewards screens to encourage ongoing engagement",
      "Designed a tablet layout adapting all key screens to larger screen sizes",
      "Built a reusable Figma component library (cards, buttons, bottom nav, badges, stats tiles)",
      "Established the visual identity: bold orange brand color, clean white UI, strong typographic hierarchy",
      "Prototyped interactive flows in Figma for client review and usability walkthroughs",
    ],
    techStack: ["Figma"],
    figmaUrl: "#",
    galleryImages: [],
    mobileGalleryImages: [
      "img/champion/mobile-1.png",
      "img/champion/mobile-2.png",
      "img/champion/mobile-3.png",
      "img/champion/mobile-4.png",
      "img/champion/mobile-5.png",
      "img/champion/mobile-6.png",
      "img/champion/mobile-7.png",
      "img/champion/mobile-8.png",
      "img/champion/mobile-9.png",
      "img/champion/mobile-10.png",
    ],
    tabletGalleryImages: [
      "img/champion/tablet-1.png",
      "img/champion/tablet-2.png",
      "img/champion/tablet-3.png",
      "img/champion/tablet-4.png",
      "img/champion/tablet-5.png",
      "img/champion/tablet-6.png",
      "img/champion/tablet-7.png",
      "img/champion/tablet-8.png",
      "img/champion/tablet-9.png",
      "img/champion/tablet-10.png",
    ],
  },
];
